package main

import (
	"context"
	"firebase.google.com/go"
	"google.golang.org/api/option"
	"log"
	"time"
	"golang.org/x/oauth2/google"
	"fmt"
)

type iratto struct {
	First string
	Last string
	Born string
	Created time.Time
}

type AutoGenerated struct {
	Type                    string `json:"type"`
	ProjectID               string `json:"project_id"`
	PrivateKeyID            string `json:"private_key_id"`
	PrivateKey              string `json:"private_key"`
	ClientEmail             string `json:"client_email"`
	ClientID                string `json:"client_id"`
	AuthURI                 string `json:"auth_uri"`
	TokenURI                string `json:"token_uri"`
	AuthProviderX509CertURL string `json:"auth_provider_x509_cert_url"`
	ClientX509CertURL       string `json:"client_x509_cert_url"`
}

func main() {
	ctx := context.Background()

	jsonData := []byte(`xxxxxx`)

	creds, err := google.CredentialsFromJSON(ctx,jsonData,"https://www.googleapis.com/auth/cloud-platform")
	if err != nil {
		fmt.Println(err)
	}
	opt := option.WithCredentials(creds)

	//opt := option.WithCredentialsFile("/Users/v00136/code/go/src/go_iot_lambda/firebase_secret_key.json")
	app, err := firebase.NewApp(ctx, nil, opt)
	if err != nil {
		log.Fatalln(err)
	}

	client, err := app.Firestore(ctx)
	if err != nil {
		log.Fatalln(err)
	}
	defer client.Close()




	_, _, err = client.Collection("users").Add(ctx, iratto{
		First: "hoge",
		Last:  "fuga",
		Born:  "1982",
		Created: time.Now(),
	})
	if err != nil {
		log.Fatalf("Failed adding alovelace: %v", err)
	}

}


